### ISSUE TITLE
undefined local variable or method `user' for main:Object (NameError)

### ISSUE THREAD

**Issue by uberdave** [Sorcery/sorcery#117]
I am following the docs, but in the reset Password Section, I get the eror

**Comment by uberdave** [comment]
Now I am getting:
uninitialized constant YourMailerClass

308 309 310 311 312 313 | # Default: `nil`     #      user.reset_password_mailer = YourMailerClass       # reset password email method on your mailer class.
-- | --
Is there another tutorial or instructions fo setting up the mailer?

**Comment by uberdave** [comment]
Today I am trying to reverse all of the generations models and controllers and start over., but I have added code to things. This is an app I wrote a few years back. Excuse me, but I am totally frustrated and my next step is to redo the app with Devise, but I need current_user. This app worked flawlessly on rails 3.2.8

**Comment by uberdave** [comment]
I give up. issue is on stackoverflow 3 times.

**Comment by uberdave** [comment]
[sorcery.txt](https://github.com/Sorcery/sorcery/files/1826378/sorcery.txt)

**Comment by uberdave** [comment]
class SorceryCore < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :email,            :null => false
      t.string :crypted_password, :null => false
      t.string :salt,             :null => false

      t.timestamps
    end

    add_index :users, :email, unique: true
  end
end

**Comment by uberdave** [comment]
user.rb

class User < ActiveRecord::Base
  authenticates_with_sorcery!

 attr_accessible :email, :password, :password_confirmation, :authentications_attributes, :image
  authenticates_with_sorcery! do |config|
  config.authentications_class = Authentication
  end
  
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
    
  	
  	
  	
  has_one :profile
  has_many :posts
  
  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

end

**Comment by uberdave** [comment]
UsersController

class UsersController < ApplicationController
   
skip_before_action :require_login, only: [:index, :new, :create, :activate]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { render action: "thanks", notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
  end
  def activate
  if (@user = User.load_from_activation_token(params[:id]))
    @user.activate!
    redirect_to(login_path, :notice => 'User was successfully activated.')
  else
    not_authenticated
  end
end
def thanks
respond_to do |format|
      format.html # thanks.html.erb
      format.json { render json: @user }
    end
end

**Comment by uberdave** [comment]
rails g mailer UserMailer reset_password_email
Traceback (most recent call last):
	33: from script/rails:6:in `<main>'
	32: from script/rails:6:in `require'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:50:in `generate'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	21: from /home/david/geofly/geofly/config/environment.rb:7:in `<top (required)>'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
	16: from /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	15: from /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	14: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	13: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
	12: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
	11: from /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	10: from /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 9: from /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 8: from /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/sorcery-0.8.6/lib/sorcery/engine.rb:11:in `block in <class:Engine>'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/sorcery-0.8.6/lib/sorcery/engine.rb:11:in `include'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/sorcery-0.8.6/lib/sorcery/controller.rb:15:in `included'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/sorcery-0.8.6/lib/sorcery/controller.rb:209:in `configure!'
/home/david/geofly/geofly/config/initializers/sorcery.rb:10:in `block in <top (required)>': undefined local variable or method `user' for main:Object (NameError)

**Comment by uberdave** [comment]
redifined as  user.reset_password_mailer = UserMailer
i
