### ISSUE TITLE
Can't remove crypted_password or salt from User model

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#12]
```
NoMethodError:
       undefined method `crypted_password' for #<User:0x007fac4838f918>
       Did you mean?  encrypt_password
     # /Users/jbuker/.rvm/gems/ruby-2.3.1/gems/sorcery-0.9.1/lib/sorcery/model.rb:146:in `external?'
     # /Users/jbuker/.rvm/gems/ruby-2.3.1/gems/sorcery-0.9.1/lib/sorcery/model/submodules/user_activation.rb:127:in `send_activation_success_email?'
     # /Users/jbuker/.rvm/gems/ruby-2.3.1/gems/sorcery-0.9.1/lib/sorcery/model/submodules/user_activation.rb:111:in `activate!'
```

For my particular use-case, I need users that only authenticate with external providers. Currently it works, but if I try to remove the `crypted_password` and/or `salt` fields from `User`, it gives this error. I tried setting the config to use `nil` or `''` instead, but that also gives errors.

When we figure out how to go forward with the modularization, we should have the option to exclude the usual crypted_password setup.

**Comment by athix** [comment]
This issue (#12) should be considered if we do try addressing: #217
