### ISSUE TITLE
Error with 0.13.0

### ISSUE THREAD

**Issue by Nerian** [Sorcery/sorcery#162]
### Configuration

- Sorcery Version: `0.13.0`
- Ruby Version: `2.5.3p105`
- Framework: `Ruby on Rails`
- Platform: `Mac OS`

Hi,

I upgraded to 0.13.0 and I get an error:

````
➜  coku-app git:(master) ✗  rspec spec/interactors/account/join_spec.rb

An error occurred while loading ./spec/interactors/account/join_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
  undefined method `helper' for ActionController::API:Class
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/effective_datatables-4.3.11/lib/effective_datatables/engine.rb:10:in `block (2 levels) in <class:Engine>'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1.1/lib/action_controller/api.rb:147:in `<class:API>'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1.1/lib/action_controller/api.rb:89:in `<module:ActionController>'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1.1/lib/action_controller/api.rb:7:in `<top (required)>'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `block in require'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/sorcery-0.13.0/lib/sorcery/engine.rb:13:in `block in <class:Engine>'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:32:in `run'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/Nerian/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:6:in `require'
# ./spec/rails_helper.rb:6:in `<top (required)>'
# ./spec/interactors/account/join_spec.rb:1:in `require'
# ./spec/interactors/account/join_spec.rb:1:in `<top (required)>'
````

There seem to be a problem between EffectiveDatatable and Sorcery regarding the initialization process.

This is how EffectiveDatatable does the initialization:

https://github.com/code-and-effect/effective_datatables/blob/master/lib/effective_datatables/engine.rb

And Sorcery:

https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/engine.rb

Sorcery 0.13.0 was working fine. This is the commit that broke it:

https://github.com/Sorcery/sorcery/commit/ae83ac3181aed9696bf78ceabcce96bf735fd7ea

Shouldn't it be using the block `ActiveSupport.on_load(:action_controller)`?

**Comment by athix** [comment]
`ActiveSupport.on_load` was causing issues where the controller was never properly included for `ActionController::Base`.

It looks like the problem is that the API controller doesn't support `helper`, and it's being accidentally included [here](https://github.com/code-and-effect/effective_datatables/blob/master/lib/effective_datatables/engine.rb#L10) in effective datatables. (`ActiveSupport.on_load :action_controller` will run twice, once for API and once for Base).

**Comment by Nerian** [comment]
Ah I see.

Here how Matt solved the issue:

https://github.com/code-and-effect/effective_datatables/commit/fe7be195d940cd0b8bc155d650df635826f0cdc9

So it's all fine now.

Thanks!
