### ISSUE TITLE
Using sorcery within Rails engine: `method_missing': undefined method `sorcery'

### ISSUE THREAD

**Issue by paulbernhard** [Sorcery/sorcery#246]
### Configuration

- Sorcery Version: `0.15.0`
- Ruby Version: `2.7.1`
- Framework: `Ruby on Rails 6.0.3.1`
- Platform: `Mac OS X High Sierra 10.13.6`

### Expected Behavior

I want to install *sorcery* in a mountable and namespaced Rails engine in order to provide a common authentication with a user model, session controller, etc. to other Rails applications.

### Actual Behavior

When running *sorcery*'s installation generator Rails throws an `undefined method `sorcery'` error. The initializer `config/initializers/socery.rb` is created, the model and migratuion files are missing.

Mounting the engine in a dummy app and running `dummy $ rails g sorcery:install` from the root directory of the dummy app leads to the same issue.

Removing *sorcery* from the engine's `gemspec` and adding it to the dummy `Gemfile`works as well as expected.

### Steps to Reproduce

Add sorcery to the gemspec file of a mountable Rails engine (in this case called `skrw`):

```ruby
# skrw.gemspec
spec.add_dependency "sorcery", "~> 0.15.0", ">= 0.15.0"
```

```bash
# from engine directory
skrw $ bundle install
skrw $ gem list | grep sorcery
#=> sorcery (0.15.0)
```

Run *sorcery*'s installation generator returns error:

```bash
skrw $ rails g sorcery:install
#=> /path/to/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/railtie/configuration.rb:96:in `method_missing': undefined method `sorcery' for #<Rails::Application::Configuration:0x00007ffe29afd5f0> (NoMethodError)
#=> The file /path/to/engine/app/models/skrw/user.rb does not appear to exist
```

Further `rails` commands throw the same error:

```bash
skrw $ rails s
#=> /path/to/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/railtie/configuration.rb:96:in `method_missing': undefined method `sorcery' for #<Rails::Application::Configuration:0x00007f852d3e3640> (NoMethodError)
```

Thanks!

**Comment by paulbernhard** [comment]
*Sorcery* seems to work, even with resources from the engine when the *sorcery* gem is added in the `Gemfile` of the host app instead of the engine's `gemspec`.

```ruby
# Gemfile

# Declare your gem's dependencies in skrw.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.
gem "sorcery", "~> 0.15.0", ">= 0.15.0"
```

```ruby
# skrw.gemspec
# …
Gem::Specification.new do |spec|
# …
  spec.add_dependency "rails", "~> 6.0.3", ">= 6.0.3.1"
  # spec.add_dependency "sorcery", "~> 0.15.0", ">= 0.15.0"
end
```

If i run `rails g sorcery:install` from the engine's root directory now, the generator executes without error messages and creates:

```
config/initializers/sorcery.rb
app/models/skrw/user.rb # already namespaced with the engine module
db/migrate/20200611105750_sorcery_core.rb
```

Now i still had to rename the `users` table in the migration file to fit to the engine's namespaced user model `Skrw::User`:

```ruby
class SorceryCore < ActiveRecord::Migration[6.0]
  def change
    create_table :skrw_users do |t|
      # …
    end
    # …
  end
end
```

and change the user model in the `sorcery.rb` initializer:

```ruby
config.user_class = "Skrw::User"
```

With this setup a basic authentication using a `SessionsController` worked out fine. The downside is still that any app using the engine will have to add *sorcery* in the `Gemfile` as it does not seem to work from the engine's `gemspec` dependencies.

**Comment by paulbernhard** [comment]
The problem was definitively not linked to *Sorcery* but just a simple mistake of not requiring *Sorcery* properly in my Rails engine. As described, the gem was properly added to the engine and listed by bundler but i forgot to `require "sorcery"` in the engine file. The solution is thus:

```ruby
# lib/skrw/engine.rb
require "sorcery"

module Skrw
  class Engine < ::Rails::Engine
    # the whole engine magic…
  end
end
```

Sorry for the fuzz, issue closed, have a good day.
