### ISSUE TITLE
Misleading deprecation warning when referencing ActionController::Base #36546

### ISSUE THREAD

**Issue by benjaminfauchald** [Sorcery/sorcery#278]
Please complete all sections.

### Configuration

- Sorcery Version: `0.16.0`
- Ruby Version: `ruby '2.7.1'`
- Framework: `6.0.3.6`
- Platform: `OSC Catalina`

### Expected Behavior

Trying to setup logger in config/enviroments/development.rb
`  # Here seems to be the place for the Logger
  config.logger = Logger.new(STDOUT)
  config.logger.level = Logger::DEBUG
`
and start rails console

Tell us what should happen.

The console should start with no errors or warnings

### Actual Behavior

console gives waring

`W, [2021-04-18T22:00:32.011188 #74501]  WARN -- : DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.`

Tell us what happens instead.

### Steps to Reproduce

This apparently is a problem with some implementations of some gem's and their interdependencies.

I added the a small gist in the env development.rb that I got from VAZFED in this [link](https://github.com/rails/rails/issues/36546) to see what could maybe cause the error / warning

```
  ActiveSupport.on_load(:action_controller_base) do
    bc = ActiveSupport::BacktraceCleaner.new
    bc.remove_silencers!
    bc.add_silencer { |line| line.start_with?(RbConfig::CONFIG["rubylibdir"]) }
    bc.add_silencer { |line| line =~ Regexp.union(
      *(
        %w{ bootsnap railties spring activesupport actionpack zeitwerk thor rack }.
        map{|g| /\A#{g} \([\w.]+\) /}
      ),
      /\Abin\/rails/
    )}
    trace = bc.clean(caller)
    puts "Cleaned backtrace:\n\t#{trace.join("\n\t")}\n"
    puts "Most probably the cause is: #{trace.first}"
    puts "If not - uncomment `raise` at #{__FILE__}:#{__LINE__+1}"
    # raise "i can haz full backtrace"
    exit(1)
  end
```

Even if I do not know what is the root cause the gist suggests that it could be: 

`Most probably the cause is: sorcery (0.16.0) lib/sorcery/engine.rb:16:in 'block in <class:Engine>'`

I saw some other people ha made some PR's already to gem "remotipart" and it apparently has something to do with sprockets. [More info here](https://github.com/JangoSteve/remotipart/pull/206)

Please list all steps to reproduce the issue.

Here is a full backtrace if that helps:

```

    sorcery (0.16.0) lib/sorcery/engine.rb:16:in `block in <class:Engine>'
        /Users/benjamin/Projects/morphosis_ops/config/environment.rb:5:in `<main>'
Most probably the cause is: sorcery (0.16.0) lib/sorcery/engine.rb:16:in `block in <class:Engine>'
If not - uncomment `raise` at /Users/benjamin/Projects/morphosis_ops/config/environments/development.rb:20
Traceback (most recent call last):
        82: from bin/rails:4:in `<main>'
        81: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        80: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        79: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        78: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        77: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        76: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<main>'
        75: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/command.rb:46:in `invoke'
        74: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/command/base.rb:69:in `perform'
        73: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        72: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        71: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        70: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/commands/console/console_command.rb:101:in `perform'
        69: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        68: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/command/actions.rb:28:in `require_environment!'
        67: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/application.rb:339:in `require_environment!'
        66: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
        65: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
        64: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
        63: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        62: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        61: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        60: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        59: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        58: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        57: from /Users/benjamin/Projects/morphosis_ops/config/environment.rb:5:in `<main>'
        56: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/application.rb:363:in `initialize!'
        55: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:60:in `run_initializers'
        54: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        53: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        52: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        51: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
        50: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
        49: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        48: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        47: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        46: from /Users/benjamin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        45: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:61:in `block in run_initializers'
        44: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `run'
        43: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `instance_exec'
        42: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/sorcery-0.16.0/lib/sorcery/engine.rb:16:in `block in <class:Engine>'
        41: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
        40: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
        39: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
        38: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        37: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        36: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        35: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        34: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        33: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        32: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/api.rb:7:in `<main>'
        31: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/api.rb:89:in `<module:ActionController>'
        30: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/api.rb:148:in `<class:API>'
        29: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        28: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
        27: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        26: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        25: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        24: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
        23: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
        22: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/railtie.rb:58:in `block (2 levels) in <class:Railtie>'
        21: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/railtie.rb:58:in `each'
        20: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/railtie.rb:62:in `block (3 levels) in <class:Railtie>'
        19: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
        18: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
        17: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
        16: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        15: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        14: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        13: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        12: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        11: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        10: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/base.rb:7:in `<main>'
         9: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/base.rb:166:in `<module:ActionController>'
         8: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/base.rb:268:in `<class:Base>'
         7: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
         6: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
         5: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
         4: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
         3: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
         2: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
         1: from /Users/benjamin/Projects/morphosis_ops/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/Users/benjamin/Projects/morphosis_ops/config/environments/development.rb:20:in `block (2 levels) in <main>': i can haz full backtrace (RuntimeError)


```

**Comment by athix** [comment]
Hi @benjaminfauchald.

I went down the same rabbit hole a while ago, essentially it boils down to how Sorcery was loading in the library originally.

Unfortunately I've tried fixing the issue in the v0 codebase, and it broke existing applications every single time.

I did however fix it in the Sorcery v1 rework by changing how the various files are loaded in. I'm still working on the v1 rework, but hope to get it ready for release as soon as possible.
