### ISSUE TITLE
:session_timeout broken after hard reboot of server?

### ISSUE THREAD

**Issue by Beartech** [Sorcery/sorcery#84]
Rails app using Rails 5.0.2, Thin web server, Mac OS X 10.12.6. 
I had to force-quite my web server running in Terminal.app and when I restarted everything I get the error: comparison of Float with String failed in the browser (using better_errors). In the server console it shows:
ArgumentError - comparison of Float with String failed:
  sorcery (0.10.2) lib/sorcery/controller/submodules/session_timeout.rb:49:in `sorcery_session_expired?'
  sorcery (0.10.2) lib/sorcery/controller/submodules/session_timeout.rb:40:in `validate_session'
  activesupport (5.0.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'
  activesupport (5.0.2) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
  actionpack (5.0.2) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  activesupport (5.0.2) lib/active_support/callbacks.rb:170:in `block in halting'
...
If I remove the :session_timeout module from the config file and restart it works and I can log in. As soon as I re-enable :session_timeout the same error happens. I'm stumped. I've rebooted the laptop again and still the same.

**Comment by Beartech** [comment]
My bad. I must have changed the timeout value and in the comments it says:
# -- session timeout --
  # How long in seconds to keep the session alive.
  # Default: `3600`
  #
 I took this to mean I should have been:
  config.session_timeout = '3600'
Changed it to:
  config.session_timeout = 3600
and working again.
